// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSjZSq4mmfteZqGjg_icjsf3GYeIwU9cA',
    appId: '1:396477599414:web:5079283b5d14ca3b9da017',
    messagingSenderId: '396477599414',
    projectId: 'auth-7ce39',
    authDomain: 'auth-7ce39.firebaseapp.com',
    storageBucket: 'auth-7ce39.firebasestorage.app',
    measurementId: 'G-XQW8H55C2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiVEZomuoOz0dSCLil6aaZ-XKS525Y4aw',
    appId: '1:396477599414:android:8430e52b5f5bcfbc9da017',
    messagingSenderId: '396477599414',
    projectId: 'auth-7ce39',
    storageBucket: 'auth-7ce39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhYr08np7TCzhppzc9KWlKvLWcBEFJCuY',
    appId: '1:396477599414:ios:835824a20663447a9da017',
    messagingSenderId: '396477599414',
    projectId: 'auth-7ce39',
    storageBucket: 'auth-7ce39.firebasestorage.app',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhYr08np7TCzhppzc9KWlKvLWcBEFJCuY',
    appId: '1:396477599414:ios:835824a20663447a9da017',
    messagingSenderId: '396477599414',
    projectId: 'auth-7ce39',
    storageBucket: 'auth-7ce39.firebasestorage.app',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSjZSq4mmfteZqGjg_icjsf3GYeIwU9cA',
    appId: '1:396477599414:web:13788c4c672fb1959da017',
    messagingSenderId: '396477599414',
    projectId: 'auth-7ce39',
    authDomain: 'auth-7ce39.firebaseapp.com',
    storageBucket: 'auth-7ce39.firebasestorage.app',
    measurementId: 'G-TBE88L2VK5',
  );
}
